//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GME_Custom.GME_VoucherAIF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBS_Voucher", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class TBS_Voucher : GME_Custom.GME_VoucherAIF.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal voucherAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string voucherStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((this.responseCodeField.Equals(value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal voucherAmount {
            get {
                return this.voucherAmountField;
            }
            set {
                if ((this.voucherAmountField.Equals(value) != true)) {
                    this.voucherAmountField = value;
                    this.RaisePropertyChanged("voucherAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string voucherStatus {
            get {
                return this.voucherStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.voucherStatusField, value) != true)) {
                    this.voucherStatusField = value;
                    this.RaisePropertyChanged("voucherStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GME_Custom.GME_VoucherAIF.TBS_VoucherLineModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GME_Custom.GME_VoucherAIF.TBS_VoucherModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GME_Custom.GME_VoucherAIF.TBS_Voucher))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBS_VoucherLineModel", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class TBS_VoucherLineModel : GME_Custom.GME_VoucherAIF.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime activationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kodeVoucherProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal lineNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string voucherCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal voucherValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime activationDate {
            get {
                return this.activationDateField;
            }
            set {
                if ((this.activationDateField.Equals(value) != true)) {
                    this.activationDateField = value;
                    this.RaisePropertyChanged("activationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                if ((this.expirationDateField.Equals(value) != true)) {
                    this.expirationDateField = value;
                    this.RaisePropertyChanged("expirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kodeVoucherProgram {
            get {
                return this.kodeVoucherProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.kodeVoucherProgramField, value) != true)) {
                    this.kodeVoucherProgramField = value;
                    this.RaisePropertyChanged("kodeVoucherProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal lineNum {
            get {
                return this.lineNumField;
            }
            set {
                if ((this.lineNumField.Equals(value) != true)) {
                    this.lineNumField = value;
                    this.RaisePropertyChanged("lineNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siteCode {
            get {
                return this.siteCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.siteCodeField, value) != true)) {
                    this.siteCodeField = value;
                    this.RaisePropertyChanged("siteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string voucherCode {
            get {
                return this.voucherCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.voucherCodeField, value) != true)) {
                    this.voucherCodeField = value;
                    this.RaisePropertyChanged("voucherCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal voucherValue {
            get {
                return this.voucherValueField;
            }
            set {
                if ((this.voucherValueField.Equals(value) != true)) {
                    this.voucherValueField = value;
                    this.RaisePropertyChanged("voucherValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBS_VoucherModel", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class TBS_VoucherModel : GME_Custom.GME_VoucherAIF.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kodeVoucherProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime periodEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime periodStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publisherIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int validityPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GME_Custom.GME_VoucherAIF.TBS_VMS_Status voucherStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kodeVoucherProgram {
            get {
                return this.kodeVoucherProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.kodeVoucherProgramField, value) != true)) {
                    this.kodeVoucherProgramField = value;
                    this.RaisePropertyChanged("kodeVoucherProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime periodEnd {
            get {
                return this.periodEndField;
            }
            set {
                if ((this.periodEndField.Equals(value) != true)) {
                    this.periodEndField = value;
                    this.RaisePropertyChanged("periodEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime periodStart {
            get {
                return this.periodStartField;
            }
            set {
                if ((this.periodStartField.Equals(value) != true)) {
                    this.periodStartField = value;
                    this.RaisePropertyChanged("periodStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string publisherID {
            get {
                return this.publisherIDField;
            }
            set {
                if ((object.ReferenceEquals(this.publisherIDField, value) != true)) {
                    this.publisherIDField = value;
                    this.RaisePropertyChanged("publisherID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int validityPeriod {
            get {
                return this.validityPeriodField;
            }
            set {
                if ((this.validityPeriodField.Equals(value) != true)) {
                    this.validityPeriodField = value;
                    this.RaisePropertyChanged("validityPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GME_Custom.GME_VoucherAIF.TBS_VMS_Status voucherStatus {
            get {
                return this.voucherStatusField;
            }
            set {
                if ((this.voucherStatusField.Equals(value) != true)) {
                    this.voucherStatusField = value;
                    this.RaisePropertyChanged("voucherStatus");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBS_VMS_Status", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum TBS_VMS_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GME_Custom.GME_VoucherAIF.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GME_Custom.GME_VoucherAIF.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GME_Custom.GME_VoucherAIF.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GME_Custom.GME_VoucherAIF.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GME_Custom.GME_VoucherAIF.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GME_Custom.GME_VoucherAIF.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GME_Custom.GME_VoucherAIF.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GME_Custom.GME_VoucherAIF.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="GME_VoucherAIF.TBS_AifVoucherSvc")]
    public interface TBS_AifVoucherSvc {
        
        // CODEGEN: Generating message contract since the wrapper name (TBS_AifVoucherSvcLookupRequest) of message TBS_AifVoucherSvcLookupRequest does not match the default value (lookup)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/lookup", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/lookupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GME_Custom.GME_VoucherAIF.AifFault), Action="http://tempuri.org/TBS_AifVoucherSvc/lookupAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse lookup(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/lookup", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/lookupResponse")]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse> lookupAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TBS_AifVoucherSvcRedeemRequest) of message TBS_AifVoucherSvcRedeemRequest does not match the default value (redeem)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/redeem", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/redeemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GME_Custom.GME_VoucherAIF.AifFault), Action="http://tempuri.org/TBS_AifVoucherSvc/redeemAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse redeem(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/redeem", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/redeemResponse")]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse> redeemAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TBS_AifVoucherSvcReadVoucherLineRequest) of message TBS_AifVoucherSvcReadVoucherLineRequest does not match the default value (readVoucherLine)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherLine", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/readVoucherLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GME_Custom.GME_VoucherAIF.AifFault), Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherLineAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse readVoucherLine(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherLine", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/readVoucherLineResponse")]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse> readVoucherLineAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TBS_AifVoucherSvcReadVoucherTableRequest) of message TBS_AifVoucherSvcReadVoucherTableRequest does not match the default value (readVoucherTable)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherTable", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/readVoucherTableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GME_Custom.GME_VoucherAIF.AifFault), Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherTableAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse readVoucherTable(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/readVoucherTable", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/readVoucherTableResponse")]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse> readVoucherTableAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TBS_AifVoucherSvcActivateRequest) of message TBS_AifVoucherSvcActivateRequest does not match the default value (activate)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/activate", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/activateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GME_Custom.GME_VoucherAIF.AifFault), Action="http://tempuri.org/TBS_AifVoucherSvc/activateAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse activate(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TBS_AifVoucherSvc/activate", ReplyAction="http://tempuri.org/TBS_AifVoucherSvc/activateResponse")]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse> activateAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcLookupRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcLookupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public GME_Custom.GME_VoucherAIF.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _voucherCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _siteId;
        
        public TBS_AifVoucherSvcLookupRequest() {
        }
        
        public TBS_AifVoucherSvcLookupRequest(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            this.CallContext = CallContext;
            this._voucherCode = _voucherCode;
            this._siteId = _siteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcLookupResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] response;
        
        public TBS_AifVoucherSvcLookupResponse() {
        }
        
        public TBS_AifVoucherSvcLookupResponse(GME_Custom.GME_VoucherAIF.TBS_Voucher[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcRedeemRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcRedeemRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public GME_Custom.GME_VoucherAIF.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _voucherCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _siteId;
        
        public TBS_AifVoucherSvcRedeemRequest() {
        }
        
        public TBS_AifVoucherSvcRedeemRequest(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            this.CallContext = CallContext;
            this._voucherCode = _voucherCode;
            this._siteId = _siteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcRedeemResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcRedeemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] response;
        
        public TBS_AifVoucherSvcRedeemResponse() {
        }
        
        public TBS_AifVoucherSvcRedeemResponse(GME_Custom.GME_VoucherAIF.TBS_Voucher[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcReadVoucherLineRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcReadVoucherLineRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public GME_Custom.GME_VoucherAIF.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _kodeVoucherProgram;
        
        public TBS_AifVoucherSvcReadVoucherLineRequest() {
        }
        
        public TBS_AifVoucherSvcReadVoucherLineRequest(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            this.CallContext = CallContext;
            this._kodeVoucherProgram = _kodeVoucherProgram;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcReadVoucherLineResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcReadVoucherLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public GME_Custom.GME_VoucherAIF.TBS_VoucherLineModel[] response;
        
        public TBS_AifVoucherSvcReadVoucherLineResponse() {
        }
        
        public TBS_AifVoucherSvcReadVoucherLineResponse(GME_Custom.GME_VoucherAIF.TBS_VoucherLineModel[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcReadVoucherTableRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcReadVoucherTableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public GME_Custom.GME_VoucherAIF.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _kodeVoucherProgram;
        
        public TBS_AifVoucherSvcReadVoucherTableRequest() {
        }
        
        public TBS_AifVoucherSvcReadVoucherTableRequest(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            this.CallContext = CallContext;
            this._kodeVoucherProgram = _kodeVoucherProgram;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcReadVoucherTableResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcReadVoucherTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public GME_Custom.GME_VoucherAIF.TBS_VoucherModel[] response;
        
        public TBS_AifVoucherSvcReadVoucherTableResponse() {
        }
        
        public TBS_AifVoucherSvcReadVoucherTableResponse(GME_Custom.GME_VoucherAIF.TBS_VoucherModel[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcActivateRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcActivateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public GME_Custom.GME_VoucherAIF.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _voucherCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _siteId;
        
        public TBS_AifVoucherSvcActivateRequest() {
        }
        
        public TBS_AifVoucherSvcActivateRequest(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            this.CallContext = CallContext;
            this._voucherCode = _voucherCode;
            this._siteId = _siteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TBS_AifVoucherSvcActivateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class TBS_AifVoucherSvcActivateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] response;
        
        public TBS_AifVoucherSvcActivateResponse() {
        }
        
        public TBS_AifVoucherSvcActivateResponse(GME_Custom.GME_VoucherAIF.TBS_Voucher[] response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TBS_AifVoucherSvcChannel : GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TBS_AifVoucherSvcClient : System.ServiceModel.ClientBase<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc>, GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc {
        
        public TBS_AifVoucherSvcClient() {
        }
        
        public TBS_AifVoucherSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TBS_AifVoucherSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TBS_AifVoucherSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TBS_AifVoucherSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.lookup(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest request) {
            return base.Channel.lookup(request);
        }
        
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] lookup(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse retVal = ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).lookup(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse> GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.lookupAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest request) {
            return base.Channel.lookupAsync(request);
        }
        
        public System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupResponse> lookupAsync(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcLookupRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            return ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).lookupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.redeem(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest request) {
            return base.Channel.redeem(request);
        }
        
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] redeem(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse retVal = ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).redeem(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse> GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.redeemAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest request) {
            return base.Channel.redeemAsync(request);
        }
        
        public System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemResponse> redeemAsync(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcRedeemRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            return ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).redeemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.readVoucherLine(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest request) {
            return base.Channel.readVoucherLine(request);
        }
        
        public GME_Custom.GME_VoucherAIF.TBS_VoucherLineModel[] readVoucherLine(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest();
            inValue.CallContext = CallContext;
            inValue._kodeVoucherProgram = _kodeVoucherProgram;
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse retVal = ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).readVoucherLine(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse> GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.readVoucherLineAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest request) {
            return base.Channel.readVoucherLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineResponse> readVoucherLineAsync(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherLineRequest();
            inValue.CallContext = CallContext;
            inValue._kodeVoucherProgram = _kodeVoucherProgram;
            return ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).readVoucherLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.readVoucherTable(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest request) {
            return base.Channel.readVoucherTable(request);
        }
        
        public GME_Custom.GME_VoucherAIF.TBS_VoucherModel[] readVoucherTable(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest();
            inValue.CallContext = CallContext;
            inValue._kodeVoucherProgram = _kodeVoucherProgram;
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse retVal = ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).readVoucherTable(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse> GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.readVoucherTableAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest request) {
            return base.Channel.readVoucherTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableResponse> readVoucherTableAsync(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _kodeVoucherProgram) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcReadVoucherTableRequest();
            inValue.CallContext = CallContext;
            inValue._kodeVoucherProgram = _kodeVoucherProgram;
            return ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).readVoucherTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.activate(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest request) {
            return base.Channel.activate(request);
        }
        
        public GME_Custom.GME_VoucherAIF.TBS_Voucher[] activate(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse retVal = ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).activate(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse> GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc.activateAsync(GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest request) {
            return base.Channel.activateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateResponse> activateAsync(GME_Custom.GME_VoucherAIF.CallContext CallContext, string _voucherCode, string _siteId) {
            GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest inValue = new GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvcActivateRequest();
            inValue.CallContext = CallContext;
            inValue._voucherCode = _voucherCode;
            inValue._siteId = _siteId;
            return ((GME_Custom.GME_VoucherAIF.TBS_AifVoucherSvc)(this)).activateAsync(inValue);
        }
    }
}
